close all;
clear all;
clc
r=10e3;
c=1e-7;
tip=1;
p=100;
Fig=figure('Name',' Factor de calitate',...
        'Numbertitle','off','Visible','off');
fig=figure( ...
           'Name','start', ...
           'NumberTitle','off', ...
           'Units', 'normalized',...
           'Position', [0.2 0.2 0.5 0.5],...
           'Visible','off');
i=imread('start.jpg');
image(i);
set(gca,'Position',[0 0 1 1]);
axis off;       
Bt=uicontrol('Style','text', ...
               'Units','normalized', ...
               'Position',[0.45 0.65 0.45 0.1], ...
               'FontSize',25,...
               'FontWeight','bold',...
               'String','Proiect-Grafică asistată de calculator', ...
               'backgroundcolor','w'); 
 Bt=uicontrol('Style','text', ...
               'Units','normalized', ...
               'Position',[0.25 0.45 0.7 0.1], ...
               'FontSize',25,...
               'FontWeight','bold',...
               'String','Circuite RC:Filtru trece bandă și filtru oprește bandă', ...
               'backgroundcolor','w');          
Br_t=uicontrol( ...
               'Style','text', ...
               'Units','normalized', ...
               'Position',[0.75 0.35 0.2 0.05], ...
               'FontSize',25,...
               'String','Student:Șandor Iulia', ...
               'backgroundcolor','w',...
               'Callback','close; ');           
B_s=uicontrol( ...
                'Style','pushbutton', ...
                'Units','normalized', ...
                'Position',[0.6 0.25 0.1 0.06], ...
                'String','START', ...
                'Callback','close; tip=2;filtre(tip,p,r,c,Fig)');
f=uimenu('Label','Documentație');
 uimenu(f,'Label','Documentație',...
     'Callback','open(''documentatie.pdf'')');            
uimenu(f,'Label','Bibliografie','Callback','',...
    'Separator','on',...
    'Callback','open(''bibliografie.pdf'')');   
uimenu(f,'Label','Ieșire','Callback','close',...
 'Separator','on','Accelerator','Q');

set(fig, 'Visible', 'on');
    